DROP SCHEMA IF EXISTS steam CASCADE;


CREATE SCHEMA steam;

CREATE TABLE steam.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

create table steam.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    country VARCHAR(100) NOT NULL,
    found_year SMALLINT NOT NULL
);

CREATE TABLE steam.games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,

    developer_id BIGINT NOT NULL REFERENCES steam.companies(id),
    publisher_id BIGINT REFERENCES steam.companies(id),

    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    release_date DATE,
    description TEXT,

    CHECK (price >= 0)
);

CREATE TABLE steam.genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE steam.game_genres (
    game_id BIGINT NOT NULL REFERENCES steam.games(id),
    genre_id BIGINT NOT NULL REFERENCES steam.genres(id),
    PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE steam.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES steam.users(id),
    purchased_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(10, 2) NOT NULL,

    CHECK (total_amount >= 0)
);

CREATE TABLE steam.purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL
        REFERENCES steam.purchases(id)
        ON DELETE CASCADE,

    game_id BIGINT NOT NULL
        REFERENCES steam.games(id),

    price_at_purchase NUMERIC(10, 2) NOT NULL, -- не steam.games.price так как цена может меняться после покупки

    CHECK (price_at_purchase >= 0),

    UNIQUE (purchase_id, game_id)
);

CREATE TABLE steam.library_entries (
    user_id BIGINT NOT NULL
        REFERENCES steam.users(id)
        ON DELETE CASCADE,

    game_id BIGINT NOT NULL
        REFERENCES steam.games(id)
        ON DELETE CASCADE,

    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    playtime_minutes INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (user_id, game_id),

    CHECK (playtime_minutes >= 0)
);

CREATE TABLE steam.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL
        REFERENCES steam.users(id)
        ON DELETE CASCADE,

    game_id BIGINT NOT NULL
        REFERENCES steam.games(id)
        ON DELETE CASCADE,

    is_positive BOOLEAN NOT NULL,
    review_text TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (user_id, game_id)
);

CREATE TABLE steam.friendships (
    user_id BIGINT NOT NULL
        REFERENCES steam.users(id)
        ON DELETE CASCADE,

    friend_id BIGINT NOT NULL
        REFERENCES steam.users(id)
        ON DELETE CASCADE,

    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, friend_id),

    CHECK (user_id <> friend_id),

    CHECK (status IN ('pending', 'accepted', 'blocked'))
);

CREATE TABLE steam.wishlist_entries (
    user_id BIGINT NOT NULL REFERENCES steam.users(id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES steam.games(id) ON DELETE CASCADE,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, game_id)
);
